-- MySQL Script generated by MySQL Workbench
-- Thu Sep  9 23:37:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema challenge_store_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `challenge_store_db` ;

-- -----------------------------------------------------
-- Schema challenge_store_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `challenge_store_db` DEFAULT CHARACTER SET utf8 ;
USE `challenge_store_db` ;

-- -----------------------------------------------------
-- Table `challenge_store_db`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `challenge_store_db`.`store` ;

CREATE TABLE IF NOT EXISTS `challenge_store_db`.`store` (
  `id_store` CHAR(36) NOT NULL,
  `photo_path` TEXT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id_store`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `challenge_store_db`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `challenge_store_db`.`product` ;

CREATE TABLE IF NOT EXISTS `challenge_store_db`.`product` (
  `id_product` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id_product`),
  CONSTRAINT `fk_product_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `challenge_store_db`.`store` (`id_store`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_store1_idx` ON `challenge_store_db`.`product` (`store_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `challenge_store_db`.`store_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `challenge_store_db`.`store_account` ;

CREATE TABLE IF NOT EXISTS `challenge_store_db`.`store_account` (
  `id_store_account` CHAR(36) NOT NULL,
  `store_account_id` CHAR(36) NOT NULL,
  `email` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id_store_account`),
  CONSTRAINT `fk_seller_store1`
    FOREIGN KEY (`store_account_id`)
    REFERENCES `challenge_store_db`.`store` (`id_store`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_seller_store1_idx` ON `challenge_store_db`.`store_account` (`store_account_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `challenge_store_db`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `challenge_store_db`.`order` ;

CREATE TABLE IF NOT EXISTS `challenge_store_db`.`order` (
  `id_order` CHAR(36) NOT NULL,
  `order_num` VARCHAR(20) NULL,
  PRIMARY KEY (`id_order`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `challenge_store_db`.`order_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `challenge_store_db`.`order_has_product` ;

CREATE TABLE IF NOT EXISTS `challenge_store_db`.`order_has_product` (
  `order_has_product_id` CHAR(36) NOT NULL,
  `order_id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`order_has_product_id`),
  CONSTRAINT `fk_product_has_order_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `challenge_store_db`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_order_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `challenge_store_db`.`order` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_has_order_order1_idx` ON `challenge_store_db`.`order_has_product` (`order_id` ASC) VISIBLE;

CREATE INDEX `fk_product_has_order_product_idx` ON `challenge_store_db`.`order_has_product` (`product_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `challenge_store_db`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `challenge_store_db`.`customer` ;

CREATE TABLE IF NOT EXISTS `challenge_store_db`.`customer` (
  `id_customer` CHAR(36) NOT NULL,
  `photo_path` TEXT NULL,
  `name` VARCHAR(45) NOT NULL,
  `id_reg_num` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_customer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `challenge_store_db`.`customer_has_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `challenge_store_db`.`customer_has_order` ;

CREATE TABLE IF NOT EXISTS `challenge_store_db`.`customer_has_order` (
  `customer_id_customer` CHAR(36) NOT NULL,
  `order_id_order` CHAR(36) NOT NULL,
  PRIMARY KEY (`customer_id_customer`, `order_id_order`),
  CONSTRAINT `fk_customer_has_order_customer1`
    FOREIGN KEY (`customer_id_customer`)
    REFERENCES `challenge_store_db`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_has_order_order1`
    FOREIGN KEY (`order_id_order`)
    REFERENCES `challenge_store_db`.`order` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_customer_has_order_order1_idx` ON `challenge_store_db`.`customer_has_order` (`order_id_order` ASC) VISIBLE;

CREATE INDEX `fk_customer_has_order_customer1_idx` ON `challenge_store_db`.`customer_has_order` (`customer_id_customer` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `challenge_store_db`.`product_photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `challenge_store_db`.`product_photo` ;

CREATE TABLE IF NOT EXISTS `challenge_store_db`.`product_photo` (
  `id_product_photo` CHAR(36) NOT NULL,
  `path` TEXT NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id_product_photo`),
  CONSTRAINT `fk_product_photo_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `challenge_store_db`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_product_photo_product1_idx` ON `challenge_store_db`.`product_photo` (`product_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
